---
- name: install python-dev
  sudo: yes
  apt: name=python-dev

- name: create virtualenv if not exist
  sudo: yes
  sudo_user: "{{schemup_user}}"
  command: virtualenv env
  args:
    chdir: "{{schemup_virtualenv_path}}"
    creates: "{{schemup_virtualenv_path}}/env"

- name: copy schemup requirements file to server
  sudo: yes
  sudo_user: "{{schemup_user}}"
  copy: src=requirements.txt dest=~/schemup-requirements.txt

- name: install schemup requirements
  sudo: yes
  sudo_user: "{{schemup_user}}"
  pip: requirements=~/schemup-requirements.txt virtualenv={{schemup_virtualenv_path}}/env
